import { delay, of } from "rxjs";
import { Player } from "../interface/player.interface";

export const _players: Player[] = [
  {
    _id: '63773646569ad80eb19e7c84',
    name: 'Anh Pi xin chào',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 1,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7c85',
    name: 'Anh Long Đẹp Chai',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 2,
    selected: false,
    quote: 'Ở cái xã hội này, có làm thì mới có ăn...',
  },
  {
    _id: '63773646569ad80eb19e7c86',
    name: 'Anh Nathan 40 tuổi',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 3,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7c87',
    name: 'Đối tượng Lâm Tuấn Phong ngụ Quận 8',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 4,
    selected: false,
    quote:
      'Đệ tử Châu Nhuận Phát. Chuyên tổ chức cờ bạc, cá độ, poker, nhậu nhẹt...',
  },
  {
    _id: '63773646569ad80eb19e7c88',
    name: 'Trung Quận 9',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 5,
    selected: false,
    quote: 'Hết hồn chưa bà zà !!!',
  },
  {
    _id: '63773646569ad80eb19e7c89',
    name: 'Ivy Cuteeeeeeeeeeeeee',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 6,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7c8a',
    name: 'Shelby Pham',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 7,
    selected: false,
    quote: 'Má em dặn là, con gái phải điệu đà.',
  },
  {
    _id: '63773646569ad80eb19e7c8b',
    name: 'Sarah Pham -  Tác giả chuỗi "Palomino1!"',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 8,
    selected: false,
    quote: 'Cho chị xin mấy cái bịch được khonggggg >-<',
  },
  {
    _id: '63773646569ad80eb19e7c8c',
    name: 'Joe Phung',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 9,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7c8d',
    name: 'Anh Thành Đại Gia tổ yến',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 10,
    selected: false,
    quote:
      'Bà con ai thèm chim yến, cua Cà Mau, gọi cho tôi. Tôi ship tận giường!!!',
  },
  {
    _id: '63773646569ad80eb19e7c8e',
    name: 'Bonnie Nguyen',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 11,
    selected: false,
    quote: 'Em chỉ cười với mỗi anh thôi đó <3',
  },
  {
    _id: '63773646569ad80eb19e7c8f',
    name: 'Pinky The Big Sister',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 12,
    selected: false,
    quote: 'Ting ting ting !!!',
  },
  {
    _id: '63773646569ad80eb19e7c90',
    name: 'Trung Cá Sấu Hoa Cà',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 13,
    selected: false,
    quote:
      'Đẹp là lợi thế. Ế là kỹ năng.\nMình không có lợi thế, nhưng mình thừa kỹ năng!',
  },
  {
    _id: '63773646569ad80eb19e7c91',
    name: 'Bill Dinh',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 14,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7c92',
    name: 'Julia Do',
    avatar: '',
    star: 0,
    status: 'organization',
    number: 15,
    selected: false,
    quote: 'Chị có 1 đứa em gái chưa có chồng. Chị cũng vậy!!!',
  },
  {
    _id: '63773646569ad80eb19e7c93',
    name: 'Jaime Do',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 16,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7c94',
    name: 'Anh chàng mạng Kim - Tín Hoàng',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 17,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7c95',
    name: 'Harry Hoang - anh Sách Giáo Khoa',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 18,
    selected: false,
    quote:
      'Keep your best wishes and your biggest goals close to your heart and dedicate time to them every day. If you truly care about what you do and you work diligently at it, there’s almost nothing you can’t accomplish.',
  },
  {
    _id: '63773646569ad80eb19e7c96',
    name: 'Khang - Cơm trưa dưới căn tin là ngon nhất',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 19,
    selected: false,
    quote: 'Nghe nói em thích người chung thủy? Còn anh vẫn là fan MU đây!',
  },
  {
    _id: '63773646569ad80eb19e7c97',
    name: 'Tuấn Tiền Trảm hậu tấu',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 20,
    selected: false,
    quote: 'Trai hư anh không phải diễn, nhưng trai tốt anh phải vào vai <3',
  },
  {
    _id: '63773646569ad80eb19e7c98',
    name: 'Neith Hoang - ông trùm Grab food, Now food, Shopee food',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 21,
    selected: false,
    quote: 'Chỉ cần có tôi, không ai phải chết đói cả.',
  },
  {
    _id: '63773646569ad80eb19e7c99',
    name: 'Joey Le anh chàng đeo kính',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 22,
    selected: false,
    quote:
      'Năm đó... chỉ vì thích một người, mà tôi đem lòng yêu cả Contemi <3',
  },
  {
    _id: '63773646569ad80eb19e7c9a',
    name: 'Trong Lu - người hướng nội',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 23,
    selected: false,
    quote: 'Nothing to say!',
  },
  {
    _id: '63773646569ad80eb19e7c9b',
    name: 'Red Ly',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 24,
    selected: false,
    quote: 'Còn thở là còn gỡ. Dừng lại là thất bại!!!',
  },
  {
    quote: '',
    _id: '63773646569ad80eb19e7c9c',
    name: 'Edward Nguyen',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 25,
    selected: false,
  },
  {
    _id: '63773646569ad80eb19e7c9d',
    name: 'Bờ rút ',
    avatar: '',
    star: 0,
    status: 'organization',
    number: 26,
    selected: false,
    quote: 'Nguyện giảm cân nhưng không bỏ bữa xế',
  },
  {
    _id: '63773646569ad80eb19e7c9e',
    name: 'Henry Nguyen',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 27,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7c9f',
    name: 'William người không tuổi',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 28,
    selected: false,
    quote: 'Khí chất là thứ trường tồn với thời gian',
  },
  {
    _id: '63773646569ad80eb19e7ca0',
    name: 'Peter Nguyen',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 29,
    selected: false,
    quote: 'Mình đến từ Bạc Liêu!',
  },
  {
    _id: '63773646569ad80eb19e7ca1',
    name: 'Felix Nguyen',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 30,
    selected: false,
    quote: 'Em ơi đừng cười nữa, đui mắt anh ლ',
  },
  {
    quote: '',
    _id: '63773646569ad80eb19e7ca2',
    name: 'Jolie Nguyen',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 31,
    selected: false,
  },
  {
    _id: '63773646569ad80eb19e7ca3',
    name: 'Ellie Nguyen',
    avatar: '',
    star: 0,
    status: 'organization',
    number: 32,
    selected: false,
    quote: 'Thị Hương em Thị Hường',
  },
  {
    quote: '',
    _id: '63773646569ad80eb19e7ca4',
    name: 'Anna Nguyen',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 33,
    selected: false,
  },
  {
    quote: '',
    _id: '63773646569ad80eb19e7ca5',
    name: 'Hanh Nguyen',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 34,
    selected: false,
  },
  {
    _id: '63773646569ad80eb19e7ca6',
    name: 'Cô Tiên Sofia',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 35,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7ca7',
    name: 'Harvey mới thất tình xong',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 36,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7ca8',
    name: 'Tom - người hát tình ca',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 37,
    selected: false,
    quote: 'Nhà anh có cái bàn thờ. Nhang đèn đầy đủ chỉ chờ mỗi em <3',
  },
  {
    quote: '',
    _id: '63773646569ad80eb19e7ca9',
    name: 'Liam Nguyen',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 38,
    selected: false,
  },
  {
    _id: '63773646569ad80eb19e7caa',
    name: 'Nam Vương của chị em',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 39,
    selected: false,
    quote: 'Quán quân Nam Vương 2018, missss, gờ rennnnnnn, Con Tẹc Méééééééé',
  },
  {
    _id: '63773646569ad80eb19e7cab',
    name: 'Tommy Pham',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 40,
    selected: false,
    quote:
      'Rồi mọi chuyện sẽ qua. Nó không qua thì từ từ nó qua (anh Vincent nói vậy)',
  },
  {
    quote: '',
    _id: '63773646569ad80eb19e7cac',
    name: 'James Pham',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 41,
    selected: false,
  },
  {
    _id: '63773646569ad80eb19e7cad',
    name: 'Sam dịu dàng',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 42,
    selected: false,
    quote: 'Vừa mờ vừa lem. Đó chính là iem!!!',
  },
  {
    _id: '63773646569ad80eb19e7cae',
    name: 'Sơn Tạ em ghẻ Sơn Tùng',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 43,
    selected: false,
    quote: "I'm sexy and I know it",
  },
  {
    _id: '63773646569ad80eb19e7caf',
    name: 'Shark Pa trick (nickname Ba chỵch)',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 44,
    selected: false,
    quote: 'Dev là phụ. Chơi coin, chơi cá 7 màu mới là chính.',
  },
  {
    _id: '63773646569ad80eb19e7cb0',
    name: 'Mila Tran - capuchino cô cô nớt',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 45,
    selected: false,
    quote: 'Mình bắt chước loài mèo kêu nha, \nkêu cùng em MÁ MÁ MÁ MÁ',
  },
  {
    _id: '63773646569ad80eb19e7cb1',
    name: 'James Tran',
    avatar: '',
    star: 0,
    status: 'organization',
    number: 46,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7cb2',
    name: 'Hoai Tran',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 47,
    selected: false,
    quote: ' Hôm nay, bạn đã log work chưa?',
  },
  {
    _id: '63773646569ad80eb19e7cb3',
    name: 'Helen Tran',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 48,
    selected: false,
    quote: 'Em lấy tiền mặt hay chuyển khoản?',
  },
  {
    quote: '',
    _id: '63773646569ad80eb19e7cb4',
    name: 'Thang Trinh',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 49,
    selected: false,
  },
  {
    _id: '63773646569ad80eb19e7cb5',
    name: 'Terry Truong',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 50,
    selected: false,
    quote:
      'Nếu bạn chê kiểu tóc của mình thì nguyên nhân nằm ở khuôn mặt bạn!!!',
  },
  {
    _id: '63773646569ad80eb19e7cb6',
    name: 'Arsen Truong',
    avatar: '',
    star: 0,
    status: 'organization',
    number: 51,
    selected: false,
    quote: 'Không có gì quý hơn không khí.',
  },
  {
    _id: '63773646569ad80eb19e7cb7',
    name: 'Truong Nhat Tien',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 52,
    selected: false,
    quote: 'Mọi người nghe rõ em nói gì không ạ @@ ',
  },
  {
    _id: '63773646569ad80eb19e7cb8',
    name: 'Alan Vo',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 53,
    selected: false,
    quote: 'Chúc mọi người ngày nào cũng như ngày nào. Nguồn: Google',
  },
  {
    quote: '',
    _id: '63773646569ad80eb19e7cb9',
    name: 'Lê Văn Tùng',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 54,
    selected: false,
  },
  {
    _id: '63773646569ad80eb19e7cba',
    name: 'Phan Thanh',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 55,
    selected: false,
    quote: 'Dượng đây hê hê hê',
  },
  {
    _id: '63773646569ad80eb19e7cbb',
    name: 'Leone Nguyen',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 56,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7cbc',
    name: 'Phạm Hà Giang',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 57,
    selected: false,
    quote: 'Nắng quá má uiii',
  },
  {
    _id: '63773646569ad80eb19e7cbd',
    name: 'Trần Kim Giao',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 58,
    selected: false,
    quote: 'Mẹ bảo cười phải tươi. Hè hè hè',
  },
  {
    _id: '63773646569ad80eb19e7cbe',
    name: 'Elvis Truong',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 59,
    selected: false,
    quote: 'Anh tuy bắt bóng giỏi nhưng bắt em là điều anh giỏi nhất :3',
  },
  {
    _id: '63773646569ad80eb19e7cbf',
    name: 'Tiêu Trường Đạt',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 60,
    selected: false,
    quote: 'Chào các bạn, mình là Đạt đến từ Đà Lạt',
  },
  {
    _id: '63773646569ad80eb19e7cc0',
    name: 'Tony the Thanos',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 61,
    selected: false,
    quote: 'Tony đây!',
  },
  {
    quote: '',
    _id: '63773646569ad80eb19e7cc1',
    name: 'Vita Bui',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 62,
    selected: false,
  },
  {
    _id: '63773646569ad80eb19e7cc2',
    name: 'Emma Nguyen',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 63,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7cc3',
    name: 'Vincent Truong',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 64,
    selected: false,
    quote: 'Anh phải về với vợ con anh ...',
  },
  {
    _id: '63773646569ad80eb19e7cc4',
    name: 'Bùi Minh Đức',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 65,
    selected: false,
    quote: 'Hi em, anh đến từ Hà Nội ...',
  },
  {
    _id: '63773646569ad80eb19e7cc5',
    name: 'David Dang',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 66,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7cc6',
    name: 'Mira Dao',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 67,
    selected: false,
    quote: 'Chè nha đam đậu xanh ngon không cả nhà',
  },
  {
    _id: '63773646569ad80eb19e7cc7',
    name: 'Anton Hoang',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 68,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7cc8',
    name: 'Kevin Hoang',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 69,
    selected: false,
    quote: 'Làm nail là chính, code là phụ thuiiiii',
  },
  {
    _id: '63773646569ad80eb19e7cc9',
    name: 'Michelle Huynh',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 70,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7cca',
    name: 'Cuong Ly',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 71,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7ccb',
    name: 'Harris Nguyen',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 72,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7ccc',
    name: 'Nguyễn Minh Tuấn',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 73,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7ccd',
    name: 'Ianna Nguyen',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 74,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7cce',
    name: 'Ryan Nguyen',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 75,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7ccf',
    name: 'Lang Phan',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 76,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7cd0',
    name: 'Trần Hữu Tước',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 77,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7cd1',
    name: 'Mi Tran',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 78,
    selected: false,
    quote: '',
  },
  {
    _id: '63773646569ad80eb19e7cd2',
    name: 'Samantha Tran',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 79,
    selected: false,
    quote: 'Sinh nhật ngày Nhà giáo nhưng hay chửi thề @@ ',
  },
  {
    _id: '6386c99bd3aa354b8fd634e3',
    name: 'Andrew Vo',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 80,
    selected: false,
    quote: 'Thị Hương em Thị Hường',
  },
  {
    _id: '63773646569ad80eb19e7c83',
    name: 'Anne Vu',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 81,
    selected: false,
    quote: 'Thị Hương em Thị Hường',
  },
  {
    _id: '63870a7d2a6b1fd36047e276',
    name: 'Chang Duong',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 82,
    selected: false,
    quote: '...',
  },
];

/**
 * JSON generator syntax
 *
[
  '{{repeat(63)}}',
  {
    name: '{{firstName()}} {{surname()}}',
    status: 'alive',
    number:  function (tags) {
      return tags.index();
    },
    avatar: function (tags) {
      return tags.index() + '.png';
    },
    star: 0,
    selected: false
  }
]

*/
