import { Player } from "../interface/player.interface";

export const _players: Player[] = [
  {
    _id: '63773646569ad80eb19e7c84',
    name: 'Anh Pi xin chào',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 1,
    selected: false,
    quote: 'Hứa trúng coin mời nước cả công ty!',
  },
  {
    _id: '63773646569ad80eb19e7c85',
    name: 'Thầy giáo Long',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 2,
    selected: false,
    quote: 'Ở cái xã hội này, có làm thì mới có ăn...',
  },
  {
    _id: '63773646569ad80eb19e7c86',
    name: 'Anh Nathan 40 tuổi',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 3,
    selected: false,
    quote: 'Nay có gì ăn không Rút???',
  },
  {
    _id: '63773646569ad80eb19e7c87',
    name: 'Roger Lam - Nhà cái đến từ Quận 8',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 4,
    selected: false,
    quote: '“Anh em tin tôi, tôi dẫn anh em về bờ”',
  },
  {
    _id: '63773646569ad80eb19e7c88',
    name: 'Trung Quận 9',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 5,
    selected: false,
    quote: 'Anh Tuấn Phong mãi đĩnnnn!!!',
  },
  {
    _id: '63773646569ad80eb19e7c89',
    name: 'Ivy Cuteeeeeeeeeeeeee',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 6,
    selected: false,
    quote: 'Em hong phải hột me, nhưng em ku teee',
  },
  {
    _id: '63773646569ad80eb19e7c8a',
    name: 'Shelby Pham',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 7,
    selected: false,
    quote: 'Má em dặn là, con gái phải điệu đà.',
  },
  {
    _id: '63773646569ad80eb19e7c8b',
    name: 'Sarah Pham -  Tác giả chuỗi "Palomino1!"',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 8,
    selected: false,
    quote: 'Cho chị xin mấy cái bịch được khonggggg >-<',
  },
  {
    _id: '63773646569ad80eb19e7c8c',
    name: 'Anh Joe lead Mobile',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 9,
    selected: false,
    quote:
      'Thế giới có 2 loại người: loại người dùng web, loại người dùng Mobile!',
  },
  {
    _id: '63773646569ad80eb19e7c8d',
    name: 'Anh Thành Đại Gia tổ yến',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 10,
    selected: false,
    quote:
      'Bà con ai thèm chim yến, cua Cà Mau, gọi cho tôi. Tôi ship tận giường!!!',
  },
  {
    _id: '63773646569ad80eb19e7c8e',
    name: 'Bonnie Nguyen',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 11,
    selected: false,
    quote: 'Em chỉ cười với mỗi anh thôi đó <3',
  },
  {
    _id: '63773646569ad80eb19e7c8f',
    name: 'Chị Hường quyền lực',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 12,
    selected: false,
    quote: 'Ting ting ting !!!',
  },
  {
    _id: '63773646569ad80eb19e7c90',
    name: 'Trung Cá Sấu Hoa Cà',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 13,
    selected: false,
    quote: 'Nhiều người hỏi tôi sao vẫn một mình. Ủa chứ nửa mình sống sao!?',
  },
  {
    _id: '63773646569ad80eb19e7c91',
    name: 'Bill Dinh',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 14,
    selected: false,
    quote: 'Anh âm thầm lặng lẽ bởi vì anh đang bận ... ăn ><',
  },
  {
    _id: '63773646569ad80eb19e7c92',
    name: 'Julia Do',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 15,
    selected: false,
    quote: 'Chị có 1 đứa em gái chưa có chồng. Chị cũng vậy!!!',
  },
  {
    _id: '63773646569ad80eb19e7c93',
    name: 'Jaime Do hay đau bụng',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 16,
    selected: false,
    quote: 'Đến cuối cùng, người đau lòng nhất vẫn là người bị đau dạ dày...',
  },
  {
    _id: '63773646569ad80eb19e7c94',
    name: 'Anh chàng mạng Kim - Tín Hoàng',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 17,
    selected: false,
    quote: 'Chữ Tín luôn phải đặt lên hàng đầu nghe quí vị!!!',
  },
  {
    _id: '63773646569ad80eb19e7c95',
    name: 'Hoàng Kiến Thiết',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 18,
    selected: false,
    quote:
      'Anh giống như trò chơi xổ số vậy. Lấy được anh là em trúng độc đắc!',
  },
  {
    _id: '63773646569ad80eb19e7c96',
    name: 'Khang, thích ăn cơm dưới căn tin',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 19,
    selected: false,
    quote: 'Nghe nói em thích người chung thủy? Anh vẫn là Fan MU đây!',
  },
  {
    _id: '63773646569ad80eb19e7c97',
    name: 'Tuấn Tiền Trảm hậu tấu',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 20,
    selected: false,
    quote: 'Trai hư anh không phải diễn, nhưng trai tốt anh phải vào vai <3',
  },
  {
    _id: '63773646569ad80eb19e7c98',
    name: 'Neith - ông trùm Grab food, Now food, Shopee food',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 21,
    selected: false,
    quote: 'Chỉ cần có tôi, không ai phải chết đói cả.',
  },
  {
    _id: '63773646569ad80eb19e7c99',
    name: 'Joo Ỳ',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 22,
    selected: false,
    quote: 'Làm ở Contemi chỉ vì đam mê, còn mê gì thì không nói @@',
  },
  {
    _id: '63773646569ad80eb19e7c9a',
    name: 'Trong Lu - người hướng nội',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 23,
    selected: false,
    quote: "Nothing to say.... By the way, I'm not gay!",
  },
  {
    _id: '63773646569ad80eb19e7c9b',
    name: 'Red Ly',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 24,
    selected: false,
    quote: 'Cùi bắp',
  },
  {
    _id: '63773646569ad80eb19e7c9c',
    name: 'Mr. Edward Nguyen',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 25,
    selected: false,
    quote: 'Hiền lành, ít nói, yêu mèo, thich màu tím, nhưng không gay!',
  },
  {
    _id: '63773646569ad80eb19e7c9d',
    name: 'Bờ rút ',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 26,
    selected: false,
    quote: 'Nguyện giảm cân nhưng không bỏ bữa xế',
  },
  {
    _id: '63773646569ad80eb19e7c9e',
    name: 'Henry Nguyen',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 27,
    selected: false,
    quote:
      'Nếu ai đó hỏi tôi về ước mơ, thì chắc là... kiếm nhiều tiền thôi :DD',
  },
  {
    _id: '63773646569ad80eb19e7c9f',
    name: 'William người không tuổi',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 28,
    selected: false,
    quote: 'Khí chất là thứ trường tồn với thời gian',
  },
  {
    _id: '63773646569ad80eb19e7ca0',
    name: 'Anh Peter Nguyen',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 29,
    selected: false,
    quote:
      'Lâu quá không gặp, có ai thấy cây dù với cái muỗng của mình còn ở công ty không?',
  },
  {
    _id: '63773646569ad80eb19e7ca1',
    name: 'Felix Nguyen',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 30,
    selected: false,
    quote: 'Em ơi đừng cười nữa, đui mắt anh ლ',
  },
  {
    _id: '63773646569ad80eb19e7ca2',
    name: 'Chị Jolie Nguyen',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 31,
    selected: false,
    quote: 'Chị Jolie yêu các iemmm!!!',
  },
  {
    _id: '63773646569ad80eb19e7ca3',
    name: 'Ellie Nguyen',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 32,
    selected: false,
    quote: 'Em là nguồn sữa cho cả công ty ~^.^~',
  },
  {
    _id: '63773646569ad80eb19e7ca4',
    name: 'Anna Nguyen',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 33,
    selected: false,
    quote: 'Anh gì ơi, má anh đánh rơi con dâu ở đây này ~.^',
  },
  {
    _id: '63773646569ad80eb19e7ca5',
    name: 'chị Hạnh',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 34,
    selected: false,
    quote: 'CÔNG, DUNG, NGÔN, HẠNH. Mình chỉ thiếu có 3 thứ hà!',
  },
  {
    _id: '63773646569ad80eb19e7ca6',
    name: 'Cô Tiên Sofia',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 35,
    selected: false,
    quote: 'Cô Tiên sẽ ban bug lành cho các con \n',
  },
  {
    _id: '63773646569ad80eb19e7ca7',
    name: 'Harvey the broken heart',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 36,
    selected: false,
    quote: 'Yêu là chết trong lòng một ít...',
  },
  {
    _id: '63773646569ad80eb19e7ca8',
    name: 'Tom, người hát tình ca',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 37,
    selected: false,
    quote: 'Nhà anh có cái bàn thờ. Nhang đèn đầy đủ chỉ chờ mỗi em <3',
  },
  {
    _id: '63773646569ad80eb19e7ca9',
    name: 'Nguyễn Văn Quyền',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 38,
    selected: false,
    quote: 'Chỉ vì tập thể dục quá sức mà giờ bị què chân!!! Ahuhu',
  },
  {
    _id: '63773646569ad80eb19e7caa',
    name: 'Nam Vương của chị em',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 39,
    selected: false,
    quote: 'Quán quân Nam Vương 2018, missss, gờ rennnnnnn, Con Tẹc Méééééééé',
  },
  {
    _id: '63773646569ad80eb19e7cab',
    name: 'Tommy dễ bảo',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 40,
    selected: false,
    quote:
      'Rồi mọi chuyện sẽ qua. Nó không qua thì từ từ nó qua (anh Vincent nói vậy)',
  },
  {
    _id: '63773646569ad80eb19e7cac',
    name: 'James suy tư',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 41,
    selected: false,
    quote: 'Đố em biết anh đang nghĩ gì?',
  },
  {
    _id: '63773646569ad80eb19e7cad',
    name: 'Sam dịu dàng',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 42,
    selected: false,
    quote: 'Vừa mờ vừa lem. Đó chính là iem!!!',
  },
  {
    _id: '63773646569ad80eb19e7cae',
    name: 'Sơn Tạ em ghẻ Sơn Tùng',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 43,
    selected: false,
    quote: "I'm sexy and I know it",
  },
  {
    _id: '63773646569ad80eb19e7caf',
    name: 'Shark Patrick (nickname Ba chuỵch)',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 44,
    selected: false,
    quote: 'Dev là phụ. Chơi coin, chơi cá 7 màu mới là chính.',
  },
  {
    _id: '63773646569ad80eb19e7cb0',
    name: 'Mila Tran - capuchino cô cô nớt',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 45,
    selected: false,
    quote: 'Mình bắt chước loài mèo kêu nha, \nkêu cùng em MÁ MÁ MÁ MÁ',
  },
  {
    _id: '63773646569ad80eb19e7cb1',
    name: 'James Tran',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 46,
    selected: false,
    quote:
      'So với việc say nắng một ai, thì anh nghĩ mình phù hợp với việc say sỉn hơn =)))',
  },
  {
    _id: '63773646569ad80eb19e7cb2',
    name: 'Ms. Hoai Tran',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 47,
    selected: false,
    quote: ' Hôm nay, bạn đã log work chưa?',
  },
  {
    _id: '63773646569ad80eb19e7cb3',
    name: 'Chị Helen kế toán',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 48,
    selected: false,
    quote: 'Em lấy tiền mặt hay chuyển khoản?',
  },
  {
    _id: '63773646569ad80eb19e7cb4',
    name: 'Mr. Thắng Trịnh',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 49,
    selected: false,
    quote: 'Muốn nghe nhạc Trịnh thì cứ bảo mình!',
  },
  {
    _id: '63773646569ad80eb19e7cb5',
    name: 'Mr. Terry - Thích vật nhau',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 50,
    selected: false,
    quote: 'Mình nhận dạy kèm Aikido nhé cả nhà',
  },
  {
    _id: '63773646569ad80eb19e7cb6',
    name: 'Arsen Truong',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 51,
    selected: false,
    quote: 'Buồn nào rồi cũng sẽ qua. Chỉ có buồn ngủ không tha ngày nào!!!',
  },
  {
    _id: '63773646569ad80eb19e7cb7',
    name: 'Nick thỏ thẻ',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 52,
    selected: false,
    quote: 'Đồng bào có nghe rõ tôi nói gì không ạ @@ ',
  },
  {
    _id: '63773646569ad80eb19e7cb8',
    name: 'Alan chú gà chăm chỉ',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 53,
    selected: false,
    quote: 'Chúc cả nhà ngày nào cũng như ngày nào. Nguồn: Google',
  },
  {
    _id: '63773646569ad80eb19e7cb9',
    name: 'Sếp Tùng',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 54,
    selected: false,
    quote: 'Anh uống dc mấy lon???',
  },
  {
    _id: '63773646569ad80eb19e7cba',
    name: 'Phan Thanh',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 55,
    selected: false,
    quote: 'Dượng đây hê hê hê',
  },
  {
    _id: '63773646569ad80eb19e7cbb',
    name: 'Leone Nguyen',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 56,
    selected: false,
    quote: 'Đang yên đang lành tự nhiên cái party, rồi noel, rồi tết. Haizzz',
  },
  {
    _id: '63773646569ad80eb19e7cbc',
    name: 'Cái Lyn',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 57,
    selected: false,
    quote: 'Nắng quá má uiii',
  },
  {
    _id: '63773646569ad80eb19e7cbd',
    name: 'Trần Kim Giao',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 58,
    selected: false,
    quote: 'Mẹ bảo con gái cười phải duyên. Hè hè hè',
  },
  {
    _id: '63773646569ad80eb19e7cbe',
    name: 'Elvis Truong',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 59,
    selected: false,
    quote: 'Anh tuy bắt bóng giỏi nhưng bắt em là điều anh giỏi nhất :3',
  },
  {
    _id: '63773646569ad80eb19e7cbf',
    name: 'Đạt Đà Lạt',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 60,
    selected: false,
    quote: 'Chào các bạn, mình là Đạt đến từ Đà Lạt',
  },
  {
    _id: '63773646569ad80eb19e7cc0',
    name: 'Tony Tèo',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 61,
    selected: false,
    quote:
      'Cái miệng anh nó vậy thôi, chứ anh là người hiền lành, nhân hậu nha mấy đứa...',
  },
  {
    _id: '63773646569ad80eb19e7cc1',
    name: 'Vita Bui',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 62,
    selected: false,
    quote: 'Ai đó làm ơn đổi cái hình khác cho em ngay !!!',
  },
  {
    _id: '63773646569ad80eb19e7cc2',
    name: 'Jack nhiều củ',
    avatar: '',
    star: 0,
    status: 'alive',
    number: 63,
    selected: false,
    quote: 'Tấm thân nhỏ bé xin chào đại gia đình!',
  },
  {
    _id: '63773646569ad80eb19e7cc3',
    name: 'Vincent the good boy',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 64,
    selected: false,
    quote: 'Anh không thích tiệc tùng, anh phải về với vợ con anh ...',
  },
  {
    _id: '63773646569ad80eb19e7cc4',
    name: 'Bùi Minh Đức',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 65,
    selected: false,
    quote: 'Anh biết em không ngại phải ra Hà Nội. Nhưng Hà Nội ngại em :))',
  },
  {
    _id: '63773646569ad80eb19e7cc5',
    name: 'David boy chung tình',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 66,
    selected: false,
    quote: 'Chân chống anh còn không thèm gạt, thì sao có thể gạt em.',
  },
  {
    _id: '63773646569ad80eb19e7cc6',
    name: 'Mira Dao',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 67,
    selected: false,
    quote: 'Dé số dé dò hông bà con cô bác ơi???',
  },
  {
    _id: '63773646569ad80eb19e7cc7',
    name: 'Anton Hoang',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 68,
    selected: false,
    quote:
      'Nuôi con khá mệt nhưng mà cũng vui chứ bộ, có điều a chốt là 3 đứa thôi.',
  },
  {
    _id: '63773646569ad80eb19e7cc8',
    name: 'Kevin vì công lý',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 69,
    selected: false,
    quote: 'Trình Global, lương Local. Yeaaaa~!',
  },
  {
    _id: '63773646569ad80eb19e7cc9',
    name: 'Michelle Huynh',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 70,
    selected: false,
    quote: 'Đeo kính chống nắng, vì sợ say anh ~.^',
  },
  {
    _id: '63773646569ad80eb19e7cca',
    name: 'Cuong Ly',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 71,
    selected: false,
    quote: 'Trên đời anh chả sợ gì chỉ sợ mỗi gái xinh!!!',
  },
  {
    _id: '63773646569ad80eb19e7ccb',
    name: 'Harris Nguyen',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 72,
    selected: false,
    quote: 'Đây là nụ cười của mình hồi còn chưa lấy vợ...',
  },
  {
    _id: '63773646569ad80eb19e7ccc',
    name: 'Nguyễn Minh Tuấn',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 73,
    selected: false,
    quote: 'Tôi yêu Contemi. Tôi yêu các bạn ❤❤❤',
  },
  {
    _id: '63773646569ad80eb19e7ccd',
    name: 'Bé Na',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 74,
    selected: false,
    quote: 'Từ khi iem lấy chồng rồi đẻ con, mọi người ít được thấy mặt iem!',
  },
  {
    _id: '63773646569ad80eb19e7cce',
    name: 'Ryan Nguyen',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 75,
    selected: false,
    quote: 'Tối qua đến giờ tắm mấy bận vẫn chưa hết mùi hành.',
  },
  {
    _id: '63773646569ad80eb19e7ccf',
    name: 'Anh Lang bể bóng',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 76,
    selected: false,
    quote: 'Quỷ sứ hàaaa',
  },
  {
    _id: '63773646569ad80eb19e7cd0',
    name: 'Oliver Trần',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 77,
    selected: false,
    quote: 'Trà sữa mẹ tạp dề ngon hôn quí vị!!',
  },
  {
    _id: '63773646569ad80eb19e7cd1',
    name: 'Chị Mi Huyền Thoại',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 78,
    selected: false,
    quote: 'Chị không biết tạo dáng, lấy hình thẻ được hônnnn',
  },
  {
    _id: '63773646569ad80eb19e7cd2',
    name: 'BA Samantha',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 79,
    selected: false,
    quote: 'Con gái chị, book chỗ trc 20 năm nữa nó thế má nó làm BA Contemi!!',
  },
  {
    _id: '6386c99bd3aa354b8fd634e3',
    name: 'Andrew thông thái',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 80,
    selected: false,
    quote: 'Người nguy hiểm thường đeo kính. Người đeo kính thường bị cận.',
  },
  {
    _id: '63773646569ad80eb19e7c83',
    name: 'Ms. Anne',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 81,
    selected: false,
    quote:
      'Công ty mình có ai  có kinh nghiệm lấy lại tài khoản facebook bị hack không?',
  },
  {
    _id: '63870a7d2a6b1fd36047e276',
    name: 'Chang Duong',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 82,
    selected: false,
    quote: 'Hi, mình tên là Trang, tên miền Tây của mình là Changgg!',
  },
  {
    _id: '639aa697660813967b0d0415',
    name: 'Emma Nguyen',
    avatar: '',
    star: 0,
    status: 'deactive',
    number: 83,
    selected: false,
    quote: 'Trên đời này em chả thiếu gì chỉ thiếu mỗi chồng tương lai <3',
  },
];
